# Generated by Django 5.0.2 on 2025-09-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_client_email_project_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ceremony_field_order',
            field=models.JSONField(blank=True, default=dict, help_text='Custom order for ceremony detail fields'),
        ),
    ]
