# Generated by Django 5.0.2 on 2025-09-18 06:52

from django.db import migrations


def populate_project_slugs(apps, schema_editor):
    """Generate slugs for existing projects"""
    Project = apps.get_model('projects', 'Project')
    
    for project in Project.objects.filter(slug=''):
        # Generate slug based on event date, type, and creation time
        event_date_str = project.event_date.strftime('%Y-%m-%d')
        creation_date_str = project.created_at.strftime('%Y%m%d-t-%H%M%S')
        type_slug = project.type.lower()
        
        # Create the slug
        slug_base = f"{event_date_str}-{type_slug}({creation_date_str})"
        
        # Ensure uniqueness by adding a counter if needed
        slug = slug_base
        counter = 1
        while Project.objects.filter(slug=slug).exclude(pk=project.pk).exists():
            slug = f"{slug_base}-{counter}"
            counter += 1
        
        project.slug = slug
        project.save()


def reverse_populate_project_slugs(apps, schema_editor):
    """Clear slugs (reverse operation)"""
    Project = apps.get_model('projects', 'Project')
    Project.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_slug'),
    ]

    operations = [
        migrations.RunPython(populate_project_slugs, reverse_populate_project_slugs),
    ]
