# Generated by Django 5.0.2 on 2025-09-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_last_admin_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
