# Generated by Django 5.0.2 on 2025-09-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivery_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_usb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_audio_recorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_external_light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_stabilizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='event_presence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='main_details',
            field=models.TextField(blank=True, help_text='Main event details', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='montage_bonus_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='montage_bonus_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='montage_highlights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='montage_movie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='montage_movie_duration',
            field=models.CharField(blank=True, choices=[('30min', '30 min'), ('1h', '1 h'), ('1h30min', '1h30min'), ('2h-3h', '2h-3h'), ('3h-4h', '3h-4h'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='montage_movie_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='package_4k',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='package_cameras',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='package_type',
            field=models.CharField(blank=True, choices=[('Clasic', 'Clasic'), ('Highlights', 'Highlights'), ('Duo', 'Duo'), ('Cinema', 'Cinema'), ('Creative', 'Creative'), ('Botez', 'Botez'), ('Custom', 'Custom')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_assistant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='team_operator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='team_videographer',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('NUNTA', 'Nunta'), ('BOTEZ', 'Botez'), ('ALTELE', 'Altele')], max_length=10),
        ),
    ]
