# Generated by Django 5.0.2 on 2025-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_delivery_online_project_delivery_usb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='package_fullhd',
            field=models.BooleanField(default=False),
        ),
    ]
