# Generated by Django 5.0.2 on 2025-09-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_package_fullhd'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='montage_cinema_duration',
            field=models.CharField(blank=True, choices=[('30min', '30 min'), ('1h30min', '1h30min')], default='1h30min', max_length=20, null=True),
        ),
    ]
