# Generated by Django 5.0.2 on 2025-09-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_montage_cinema_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='montage_cinema_duration',
            field=models.CharField(blank=True, choices=[('1h', '1 hour'), ('1h30min', '1h30min')], default='1h30min', max_length=20, null=True),
        ),
    ]
