# Generated by Django 5.0.2 on 2025-09-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_montage_cinema_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='edit_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Completed', 'Completed')], default='Not Started', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Planning', 'Planning'), ('Filming', 'Filming'), ('Editing', 'Editing'), ('Completed', 'Completed')], default='Not Started', max_length=50),
        ),
    ]
