# Generated by Django 5.0.2 on 2025-09-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_edit_status_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='editing_progress',
            field=models.IntegerField(default=0, help_text='Editing progress percentage (0-100)'),
        ),
    ]
