# Generated by Django 5.0.2 on 2025-09-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_editing_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='filming_details',
            field=models.TextField(blank=True, help_text='Details for the filming team', null=True),
        ),
    ]
