# Generated by Django 5.0.2 on 2025-10-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_fieldhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='videographer_editing_notes',
            field=models.TextField(blank=True, help_text="Videographer's notes for editing (admin only)", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='videographer_filming_notes',
            field=models.TextField(blank=True, help_text="Videographer's notes for filming (admin only)", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='filming_details',
            field=models.TextField(blank=True, help_text='Client requests for filming', null=True),
        ),
    ]
