# Generated by Django 5.0.2 on 2025-10-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_videographer_editing_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='critical_production_notes',
            field=models.TextField(blank=True, help_text='Critical production details (admin only)', null=True),
        ),
    ]
