# Generated by Django 5.0.2 on 2025-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_add_critical_production_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_guidance_message',
            field=models.CharField(default='initial', help_text='Current guidance message type', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='dismissed_guidance_messages',
            field=models.JSONField(blank=True, default=list, help_text='List of dismissed guidance message types'),
        ),
    ]
