# Generated by Django 5.0.2 on 2025-10-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_add_client_guidance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='price_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('LEI', 'Lei')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='price_other_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
