# Generated by Django 5.0.2 on 2025-10-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_price_project_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
