# Generated by Django 5.0.2 on 2025-10-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_project_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
