# Generated by Django 5.0.2 on 2025-10-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_change_price_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for video completion (admin only)', null=True),
        ),
    ]
